### ISSUE TITLE
Coding error when installing the plugin

### ISSUE THREAD

**Issue by stephanfcesa** [catalyst/moodle-enrol_auto#17] opened 2018-09-18 13:09 UTC
Hi 

I installed this plugin and got the following error: 
"Coding error detected, it must be fixed by a programmer: Block type admin has been disabled by the administrator"

This is when a learner logs in for the first time and views the course.

Can you please assist?

**Comment by bynare** [comment] 2019-02-24 21:16
Hi @stephanfcesa 

I seem unable to replicate this issue. It also does not sound like this issues is related to the plugin.
Can you provide detailed steps on how to replicate the issue you're seeing?

Thanks!

**Comment by danmarsden** [comment] 2021-02-14 20:50
closing as cannot reproduce and no further information provided by reporter.

**Closed by danmarsden** 2021-02-14 20:50 UTC
