### ISSUE TITLE
allow_manage function does not check capabilities.

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-enrol_auto#30] opened 2020-07-25 19:00 UTC
The allow_manage function always returns true, Why are the enrol/auto:manage capability settings not used?

**Comment by danmarsden** [comment] 2020-07-27 00:46
it's copied from the core enrol plugins - take a look at the core api docs which states:
" Does this plugin allow manual changes in user_enrolments table?" 

eg - it's not intended to check capabilities in this function.

the edit_enrolment() function in enrol/locallib checks allow_manage AND enrol/plugin:manage 

closing this as not a bug, but let me know if I've missed something there...

**Closed by danmarsden** 2020-07-27 00:46 UTC
