### ISSUE TITLE
Plugin does not Auto enroll students on Moodle 4.0.5  

### ISSUE THREAD

**Issue by ecottis** [catalyst/moodle-enrol_auto#35] opened 2022-11-24 11:17 UTC
I this plugin was working fine until the other day after upgrading to Moodle Version 4.0.5 (Build: 20221114)

Now it will **not** enroll learners on 'Loading a Course' 

Can you please have a look as we find this plugin very useful.

**Comment by danmarsden** [comment] 2022-11-24 21:07
What version of Moodle were you previously using? - this may be a duplicate of #21 and #31

**Closed** 2022-11-24 21:10 UTC

**Comment by ecottis** [comment] 2022-11-25 06:31
It was version moodle v 4.0.4

I uninstalled the plug-in then reinstalled and now appears to be working.  All I can think was it got corrupted when the upgrade was done.
