### ISSUE TITLE
Allows double enrolments 

### ISSUE THREAD

**Issue by tmalvern** [catalyst/moodle-enrol_auto#26] opened 2020-03-23 03:41 UTC
When a user is already enrolled in a course by the 'Self Enrolment' method, the user is re-enrolled in the same course when they login after 'Auto Enrolement' is activated.

**Comment by danmarsden** [comment] 2020-03-23 23:24
@tmalvern - this doesn't look right to me - users can be enrolled in a single course using multiple enrolment methods and in many cases this is intentional as each enrolment method may have different conditions around enrolment period etc.

I suspect the "need" for this change is related to a strangely configured course with multiple enrolment methods. You mention the self-enrolment plugin in your issue - typically the self-enrolment plugin is disabled when the enrol_auto is used. Can you provide a bit more on the use-case where self enrol and enrol auto are doing something useful and it doesn't just make sense to disable one?

I could see there being a use-case to hide the welcome email if the user is already enrolled, but even then I'm not completely convinced (yet)

**Comment by danmarsden** [comment] 2020-03-24 23:10
just caught up with @tmalvern - I had assumed the notification that was being sent was coming from the enrol_auto plugin, but in fact the notifications are coming from another 3rd party plugin.

The 3rd party plugin seems to have a very strange/fragile use of enrolment event handlers and the fix for duplicate notifications needs to be made to that external plugin rather than this one. There are many cases where a user can have multiple enrolment records for the same course and the external plugin should manage this better so @tmalvern is going to look at fixing it within the notification plugin - I'm now closing this one as not a bug as it relates to an issue with another plugin.

thanks!

**Closed by danmarsden** 2020-03-24 23:10 UTC
