### ISSUE TITLE
Upgrade to new Moodle versions

### ISSUE THREAD

**Issue by taraghi** [catalyst/moodle-enrol_auto#31] opened 2020-10-12 17:05 UTC
Hi,

Is there any plan to keep this plugin updated to current supported Moodle versions, 3.9, 3.8, etc?

Thanks
Beni

**Comment by danmarsden** [comment] 2020-10-13 20:44
no specific timeframe at the moment sorry. there is a patch here that might sort it though:
https://github.com/stephanepoinsart/moodle-enrol_auto/commit/1b6fdc3f8b837713be6bc919200f54c8b1112c99

**Comment by danmarsden** [comment] 2022-11-24 21:22
closing as a duplicate of #21 

you might consider using the https://moodle.org/plugins/enrol_autoenrol plugin instead.

**Closed by danmarsden** 2022-11-24 21:22 UTC
